services:
  email-oauth2-proxy:
    image: yggdrasilodin/email-oauth2-proxy:latest
    container_name: email-oauth2-proxy
    volumes:
      - ./config:/config
    # if your proxy should be accessible outside of the oauth-proxy-network uncomment, add the oauth-proxy-network to your service, which need IMAP, POP, SMTP access
    #ports:
      # IMAP Ports
      #- "${IMAP_PORT:-1143}:1143"
      #- "${IMAPS_PORT:-1993}:1993"
      # POP3 Ports
      #- "${POP3_PORT:-1110}:1110"
      #- "${POP3S_PORT:-1995}:1995"
      # SMTP Ports
      #- "${SMTP_PORT:-1025}:1025"
      #- "${SMTPS_PORT:-1587}:1587"
    env_file:
      - stack.env
    environment:
      - EMAIL_PROVIDER=${EMAIL_PROVIDER:-office365}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - REDIRECT_URI=${REDIRECT_URI:-http://localhost:12345/}
      - DEBUG_MODE=${DEBUG_MODE:-false}
    restart: unless-stopped
    networks:
      - oauth-proxy-network

networks:
  oauth-proxy-network:
    driver: bridge
